# Site settings
title: RFOFSpiderWeb.NET: The New Internet
email: your-email@example.com # Replace with your email
description: "The new internet that brings security, decentralization, and innovation to every digital interaction, powered by PRAI and PZQQET AXIOMATIKX."
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://rfof-network.github.io" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima # You can change this to null or a custom theme if you have one
# If using a custom theme, ensure your _layouts and _includes are prioritized.
# Alternatively, you can directly place _layouts and _includes in your root.
# exclude:
#   - Gemfile
#   - Gemfile.lock

# GitHub Pages settings (usually default)
defaults:
  - scope:
      path: ""
    values:
      layout: "default" # Default layout for all pages unless specified otherwise

# Permalinks for posts (if you plan to use posts)
# permalink: /:categories/:year/:month/:day/:title/

# Plugins (if you use any)
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Recommended for SEO
