theme: minima

title: Planet Rescuer Artificial Intelligence (PRAI)

author: J.K->@Satoramy-PRAI (@RFOF-NETWORK)

description: PZQQET based Comprehensive BOxchain ACT-NDT Internet decentralized comunikation & political voting system for freedom of the Planet Earth & every living on it with solutions for our Glibal Future.
